status = [
  "Build with args: ''",
  "Build with args: '-Doptimize=ReleaseSafe'",
  "Build with args: '-Doptimize=ReleaseFast'",
  "Build with args: '-Doptimize=ReleaseSmall'",
  "Test",
  "Check formatting",
]
delete_merged_branches = true
update_base_for_deletes = true
cut_body_after = "<details>"
commit_title = "chore(pull): merge ${PR_REFS}"
