status = [
  "Build via args: ''",
  "Build via args: '-Drelease-safe'",
  "Build via args: '-Drelease-fast'",
  "Build via args: '-Drelease-small'",
  "Test",
  "Check formatting",
]
delete_merged_branches = true
update_base_for_deletes = true
cut_body_after = "<details>"
commit_title = "chore(pull): merge ${PR_REFS}"
