name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    name: "Build on ${{ matrix.OS }} (via args: ${{ matrix.OPTIMIZE }})"
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        OS: [ubuntu-latest]
        OPTIMIZE: ["", "-Drelease-safe", "-Drelease-fast", "-Drelease-small"]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.10.0

      - name: Build
        run: zig build ${{ matrix.OPTIMIZE }}

      - name: Test
        run: zig build test ${{ matrix.OPTIMIZE }}

  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.10.0

      - name: Check formatting
        run: zig fmt --check .
